version: '3'
# Nama container yang kita buat
services: 
  nginx1:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "C:/Users/IT PIAT7/belajar-docker/html1:/usr/share/nginx/html"
  nginx2:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "C:/Users/IT PIAT7/belajar-docker/html1:/usr/share/nginx/html"
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "coba"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "C:/Users/IT PIAT7/belajar-docker/mysql_data:/var/lib/mysql"
    networks:
      - network1
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - network1
networks:
  network1:
    driver: bridge